name: ogurets_flutter
description:
  This package extends the Cucumber based Ogurets package to allow to support Flutter.
version: 2.0.0
authors:
  - Irina Southwell <irinasouthwell@gmail.com>
  - Richard Vowles <richard@bluetrainsoftware.com>
homepage: https://github.com/dart-ogurets/OguretsFlutter
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  ogurets: ^3.1.6
#  ogurets:
#    path: /Users/richard/projects/dart/ogurets
  flutter_driver:
    sdk: flutter
  logging: ^0.11.3+2
  commandline_splitter: ^1.5.2
  image: ^2.1.4

dev_dependencies:
  pedantic: any

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

